### ISSUE TITLE
Y no private ? 

### ISSUE THREAD

**Issue by Svieg** [FabbyD/ConUHacks#1]
Look at the title.

**Comment by lajoiepy** [comment]
On a pensé à toi pour que tu puisses stalker notre progression en fin de semaine!

**Comment by Svieg** [comment]
C'est gentil !

**Comment by fabbyd** [comment]
Parce que je cherche encore comment le mettre private pour free.

**Comment by Svieg** [comment]
T'as tu ton compte Education ? Sinon faut t'envoie un mail a GitHub avec ton mail de poly et que t'ajoutes ton mail de poly dans tes settings me semble

**Comment by fabbyd** [comment]
Y'a je viens de faire ça. J'attends.

**Comment by fabbyd** [comment]
Wow. Je me sens puissant. Je ferme la discussion puisque le repo est rendu private!
